# Tell Travis you want a Python environment to test in
language: python

# List the versions of Python you'd like to test against
python:
  - "2.6"
  - "2.7"

# List the versions of Django you'd like to test against
env:
  - DJANGO_VERSION=1.1.4
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.16
  - DJANGO_VERSION=1.5.11
  - DJANGO_VERSION=1.6.8
  - DJANGO_VERSION=1.7.1

# Tell it the things it will need to install when it boots
install:
  # This is a dependency of our Django test script
  - pip install argparse --use-mirrors
  - pip install coverage --use-mirrors
  - pip install coveralls --use-mirrors

  # Install the dependencies the app itself has
  - pip install pycrypto>=2.0.1 --use-mirrors
  # Install whatever version of Django that's listed above
  # Travis is currently working on
  - pip install -q Django==$DJANGO_VERSION --use-mirrors

# Tell Travis how to run the test script itself
script:
  coverage run --source=unfriendly quicktest.py unfriendly

after_success:
  coveralls
